[package]
name = "capnproto-test-rust"
version = "0.1.0"
authors = ["Amos Wenger <amoswenger@gmail.com>"]
edition = "2018"

[dependencies]
capnp = "0.9.4"
capnp-rpc = "0.9.0"
tokio = "0.1.18"
futures = "0.1.25"
