"use strict";
/* tslint:disable */
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * This file has been automatically generated by the [capnpc-ts utility](https://github.com/jdiaz5513/capnp-ts).
 */
const capnp = require("capnp-ts");
const capnp_ts_1 = require("capnp-ts");
exports._capnpFileId = "f707573bf7bf8fda";
class Rational extends capnp_ts_1.Struct {
    getNum() { return capnp_ts_1.Struct.getUint32(0, this); }
    setNum(value) { capnp_ts_1.Struct.setUint32(0, value, this); }
    getDen() { return capnp_ts_1.Struct.getUint32(4, this); }
    setDen(value) { capnp_ts_1.Struct.setUint32(4, value, this); }
    toString() { return "Rational_" + super.toString(); }
}
Rational._capnp = { displayName: "Rational", id: "e600925993c23cf3", size: new capnp_ts_1.ObjectSize(8, 0) };
exports.Rational = Rational;
class AudioFrame extends capnp_ts_1.Struct {
    getStreamId() { return capnp_ts_1.Struct.getUint32(8, this); }
    setStreamId(value) { capnp_ts_1.Struct.setUint32(8, value, this); }
    adoptPts(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownPts() { return capnp_ts_1.Struct.disown(this.getPts()); }
    getPts() { return capnp_ts_1.Struct.getStruct(1, Rational, this); }
    hasPts() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initPts() { return capnp_ts_1.Struct.initStructAt(1, Rational, this); }
    setPts(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    getNumSamples() { return capnp_ts_1.Struct.getUint32(0, this); }
    setNumSamples(value) { capnp_ts_1.Struct.setUint32(0, value, this); }
    getChannels() { return capnp_ts_1.Struct.getUint16(4, this); }
    setChannels(value) { capnp_ts_1.Struct.setUint16(4, value, this); }
    adoptData(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownData() { return capnp_ts_1.Struct.disown(this.getData()); }
    getData() { return capnp_ts_1.Struct.getData(0, this); }
    hasData() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initData(length) { return capnp_ts_1.Struct.initData(0, length, this); }
    setData(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    toString() { return "AudioFrame_" + super.toString(); }
}
AudioFrame._capnp = { displayName: "AudioFrame", id: "e2c181595b768329", size: new capnp_ts_1.ObjectSize(16, 2) };
exports.AudioFrame = AudioFrame;
var VideoFrame_PixelFormat;
(function (VideoFrame_PixelFormat) {
    VideoFrame_PixelFormat[VideoFrame_PixelFormat["RGBA"] = 0] = "RGBA";
})(VideoFrame_PixelFormat = exports.VideoFrame_PixelFormat || (exports.VideoFrame_PixelFormat = {}));
class VideoFrame extends capnp_ts_1.Struct {
    getStreamId() { return capnp_ts_1.Struct.getUint32(12, this); }
    setStreamId(value) { capnp_ts_1.Struct.setUint32(12, value, this); }
    adoptPts(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownPts() { return capnp_ts_1.Struct.disown(this.getPts()); }
    getPts() { return capnp_ts_1.Struct.getStruct(1, Rational, this); }
    hasPts() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initPts() { return capnp_ts_1.Struct.initStructAt(1, Rational, this); }
    setPts(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    getWidth() { return capnp_ts_1.Struct.getUint32(0, this); }
    setWidth(value) { capnp_ts_1.Struct.setUint32(0, value, this); }
    getHeight() { return capnp_ts_1.Struct.getUint32(4, this); }
    setHeight(value) { capnp_ts_1.Struct.setUint32(4, value, this); }
    getPixelFormat() { return capnp_ts_1.Struct.getUint16(8, this); }
    setPixelFormat(value) { capnp_ts_1.Struct.setUint16(8, value, this); }
    adoptData(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownData() { return capnp_ts_1.Struct.disown(this.getData()); }
    getData() { return capnp_ts_1.Struct.getData(0, this); }
    hasData() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initData(length) { return capnp_ts_1.Struct.initData(0, length, this); }
    setData(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    toString() { return "VideoFrame_" + super.toString(); }
}
VideoFrame.PixelFormat = VideoFrame_PixelFormat;
VideoFrame._capnp = { displayName: "VideoFrame", id: "d0d3ae0869b4d05c", size: new capnp_ts_1.ObjectSize(16, 2) };
exports.VideoFrame = VideoFrame;
var Frame_Which;
(function (Frame_Which) {
    Frame_Which[Frame_Which["AUDIO_FRAME"] = 0] = "AUDIO_FRAME";
    Frame_Which[Frame_Which["VIDEO_FRAME"] = 1] = "VIDEO_FRAME";
})(Frame_Which = exports.Frame_Which || (exports.Frame_Which = {}));
class Frame extends capnp_ts_1.Struct {
    adoptAudioFrame(value) {
        capnp_ts_1.Struct.setUint16(0, 0, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    disownAudioFrame() { return capnp_ts_1.Struct.disown(this.getAudioFrame()); }
    getAudioFrame() {
        capnp_ts_1.Struct.testWhich("audioFrame", capnp_ts_1.Struct.getUint16(0, this), 0, this);
        return capnp_ts_1.Struct.getStruct(0, AudioFrame, this);
    }
    hasAudioFrame() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initAudioFrame() {
        capnp_ts_1.Struct.setUint16(0, 0, this);
        return capnp_ts_1.Struct.initStructAt(0, AudioFrame, this);
    }
    isAudioFrame() { return capnp_ts_1.Struct.getUint16(0, this) === 0; }
    setAudioFrame(value) {
        capnp_ts_1.Struct.setUint16(0, 0, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    adoptVideoFrame(value) {
        capnp_ts_1.Struct.setUint16(0, 1, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    disownVideoFrame() { return capnp_ts_1.Struct.disown(this.getVideoFrame()); }
    getVideoFrame() {
        capnp_ts_1.Struct.testWhich("videoFrame", capnp_ts_1.Struct.getUint16(0, this), 1, this);
        return capnp_ts_1.Struct.getStruct(0, VideoFrame, this);
    }
    hasVideoFrame() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initVideoFrame() {
        capnp_ts_1.Struct.setUint16(0, 1, this);
        return capnp_ts_1.Struct.initStructAt(0, VideoFrame, this);
    }
    isVideoFrame() { return capnp_ts_1.Struct.getUint16(0, this) === 1; }
    setVideoFrame(value) {
        capnp_ts_1.Struct.setUint16(0, 1, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this));
    }
    toString() { return "Frame_" + super.toString(); }
    which() { return capnp_ts_1.Struct.getUint16(0, this); }
}
Frame.AUDIO_FRAME = Frame_Which.AUDIO_FRAME;
Frame.VIDEO_FRAME = Frame_Which.VIDEO_FRAME;
Frame._capnp = { displayName: "Frame", id: "9a599bfe77132e2d", size: new capnp_ts_1.ObjectSize(8, 1) };
exports.Frame = Frame;
class Frames extends capnp_ts_1.Struct {
    adoptFrames(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownFrames() { return capnp_ts_1.Struct.disown(this.getFrames()); }
    getFrames() { return capnp_ts_1.Struct.getList(0, Frames._Frames, this); }
    hasFrames() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initFrames(length) { return capnp_ts_1.Struct.initList(0, Frames._Frames, length, this); }
    setFrames(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    toString() { return "Frames_" + super.toString(); }
}
Frames._capnp = { displayName: "Frames", id: "8983a81aef3335c6", size: new capnp_ts_1.ObjectSize(0, 1) };
exports.Frames = Frames;
Frames._Frames = capnp.CompositeList(Frame);
